### ISSUE TITLE
Add to supermarket

### ISSUE THREAD

**Issue by TD-4242** [alappe/cookbook-openntpd#2]
Could you add this to the supermarket?  This is a great way to swap out ntp.

**Comment by alappe** [comment]
Hey @TD-4242,

I am glad that you like it. At the moment I don't really think this would be good though, as this cookbook is heavily outdated. Maybe you want to fork it and add it yourself? If not, I could try to polish it a bit, but this would take me a few days…

**Comment by TD-4242** [comment]
I'll look it over a little closer and see.  We were able to drop it in with only a tiny bit of wrapper.
